# Generated by Django 2.0.6 on 2018-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='musical',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
